pipeline {

    agent any

    stage("Check docker") {
        steps {
            script {
                sh 'docker --version'
                sh 'docker compose --version'
            }
        }
    }

    stages {
        stage('OWASP Dependency Check') {
            steps {
                script {
                    def dep_check = sh(script: 'mvn org.owasp:dependency-check-maven:check', returnStdout: true)
                    println dep_check
                }
            }
        }
    }
}