pipeline {

    agent any

    stages {
        stage('OWASP Dependency Check') {
            steps {
                script {
                    def dep_check = sh(script: 'mvn org.owasp:dependency-check-maven:check', returnStdout: true)
                    println dep_check
                }
            }
        }
    }
}